title: Thilanka Widanagamage
logo: https://avatars.githubusercontent.com/u/75206560?v=4
description: A passionate software engineer specializing in AI, machine learning, and web development.
theme: minimal
author: Thilanka Widanagamage
baseurl: "" # Root URL (leave blank for GitHub Pages)
url: "https://thilanka.github.io" # Your website URL
