title: Thilanka Widanagamage
# logo: https://avatars.githubusercontent.com/u/75206560?v=4
description: A passionate software engineer specializing in AI, machine learning, and web development.
show_download: true
theme: jekyll-theme-minimal
# author: Thilanka Widanagamage
# url: "https://thilanka.github.io" # Your website URL
